# Esercitazione 0

Argomenti: manipolazione di vettori e matrici, grafici di funzioni, linguaggio Matlab


In [37]:
import numpy as np
from scipy import io, integrate, linalg, signal
from scipy.sparse.linalg import eigs

## Esercizio 3

1. Definire la matrice $A=\left\lbrack \begin{array}{cccccc}
1 & 2 & 3 & 4 & 5 & 6\\
5 & 6 & 7 & 8 & 9 & 10\\
9 & 10 & 11 & 12 & 13 & 14\\
15 & 16 & 17 & 18 & 19 & 20
\end{array}\right\rbrack$
2. Costruire la matrice $B$ formata dalle colonne di $A$ disposte in ordine inverso (ossia, la prima colonna di $B$ è la sesta di $A$, la seconda di $B$ è la quinta di $A$...)
3. Costruire la matrice formata dalle sole colonne pari di $A$
4. Costruire la matrice formata dalle sole righe dispari di $A$
5. Costruire la matrice formata dalle righe 1, 4, 3 e dalle colonne 5, 2 di $A$
6. Costruire il vettore formato dagli elementi diagonali $a_{k,k}$ con $k \in \{1, \dots , 4\}$ di $A$


#### Parte 1

Definire la matrice

$A = \left\lbrack \begin{array}{cccccc}
1 & 2 & 3 & 4 & 5 & 6\\
5 & 6 & 7 & 8 & 9 & 10\\
9 & 10 & 11 & 12 & 13 & 14\\
15 & 16 & 17 & 18 & 19 & 20
\end{array}\right\rbrack$

##### Risoluzione

In [38]:
A = np.array([np.arange(1, 7),
              np.arange(5, 11),
              np.arange(9, 15),
              np.arange(15, 21)])
print(A)

[[ 1  2  3  4  5  6]
 [ 5  6  7  8  9 10]
 [ 9 10 11 12 13 14]
 [15 16 17 18 19 20]]


#### Parte 2

Costruire la matrice $B$ formata dalle colonne di $A$ disposte in ordine inverso (ossia, la prima colonna di $B$ è la sesta di $A$, la seconda di $B$ è la quinta di $A$...)

##### Risoluzione

In [39]:
B = A[:,:0:-1]
print(B)

[[ 6  5  4  3  2]
 [10  9  8  7  6]
 [14 13 12 11 10]
 [20 19 18 17 16]]


### Parte 3

Costruire la matrice formata dalle sole colonne pari di $A$

#### Risoluzione

In [40]:
APari = A[:,1::2]
print(APari)

[[ 2  4  6]
 [ 6  8 10]
 [10 12 14]
 [16 18 20]]


### Parte 4

Costruire la matrice formata dalle sole righe dispari di $A$

#### Risoluzione

In [41]:
ADispari = A[0::2,:]
print(ADispari)

[[ 1  2  3  4  5  6]
 [ 9 10 11 12 13 14]]


### Parte 5

Costruire la matrice formata dalle righe 1, 4, 3 e dalle colonne 5, 2 di $A$

#### Risoluzione

In [42]:
ARidotta = A[np.ix_([0,3,2],[4,1])]
print(ARidotta)

[[ 5  2]
 [19 16]
 [13 10]]


### Parte 6

Costruire il vettore formato dagli elementi diagonali $a_{k,k}$ con $k \in \{1, \dots, 4\}$ di $A$

#### Risoluzione

In [43]:
diagA = np.diag(A)
print(diagA)

[ 1  6 11 18]


## Esercizio 4

1. Utilizzare il comando diag di Python per definire la matrice tridiagonale $B$ di dimensione $10\times 10$, i cui elementi della diagonale principale sono tutti uguali a 5 e quelli delle codiagonali inferiore e superiore sono rispettivamente uguali a −1 e a 3
2. Quindi porre uguale a 2 gli elementi appartenenti all’intersezione delle colonne 6 e 9 e delle righe 5 e 8.

### Parte 1

Utilizzare il comando diag di Python per definire la matrice tridiagonale $B$ di dimensione $10\times 10$, i cui elementi della diagonale principale sono tutti uguali a 5 

#### Risoluzione

In [52]:
B1 = np.diag(5.0*np.ones((10)),0)
B2 = np.diag(3.0*np.ones(9),1);
B3 = np.diag(-1.0*np.ones(9),-1);
B = B1 + B2 + B3
print(B)

[[ 5.  3.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  5.  3.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  5.  3.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  5.  3.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  5.  3.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  5.  3.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  5.  3.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  5.  3.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  5.  3.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  5.]]


### Parte 2
Quindi porre uguale a 2 gli elementi appartenenti all’intersezione delle colonne 6 e 9 e delle righe 5 e 8.

#### Risoluzione

In [54]:
B[np.ix_([4,7],[5,8])] = 2.0
print(B)

[[ 5.  3.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  5.  3.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  5.  3.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  5.  3.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  5.  2.  0.  0.  2.  0.]
 [ 0.  0.  0.  0. -1.  5.  3.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  5.  3.  0.  0.]
 [ 0.  0.  0.  0.  0.  2. -1.  5.  2.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  5.  3.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  5.]]


## Esercizio 5

1. Utilizzare il comando plot di Python per rappresentare graficamente le seguenti funzioni: $$f\left(x\right)=e^{-x^2 } \;\;\mathrm{con}-5\le x\le 5$$
2. Utilizzare il comando plot di Python per rappresentare graficamente le seguenti funzioni: $$f\left(x\right)=x\;\sin \left(\frac{1}{x}\right)\;\mathrm{con}\;\;0<x\le 2$$

### Parte 1

Utilizzare il comando plot di Python per rappresentare graficamente le seguenti funzioni: $$f\left(x\right)=e^{-x^2 } \;\;\mathrm{con}-5\le x\le 5$$

#### Risoluzione

In [59]:
x = np.linspace(-5.0, 5.0, 1000)
f = lambda x: np.exp(-x**2)




[1.38879439e-11 1.53485501e-11 1.69593705e-11 1.87354905e-11
 2.06934725e-11 2.28514965e-11 2.52295142e-11 2.78494161e-11
 3.07352160e-11 3.39132500e-11 3.74123958e-11 4.12643108e-11
 4.55036924e-11 5.01685615e-11 5.53005724e-11 6.09453493e-11
 6.71528551e-11 7.39777913e-11 8.14800350e-11 8.97251142e-11
 9.87847260e-11 1.08737300e-10 1.19668614e-10 1.31672458e-10
 1.44851365e-10 1.59317399e-10 1.75193016e-10 1.92611999e-10
 2.11720473e-10 2.32678010e-10 2.55658827e-10 2.80853093e-10
 3.08468340e-10 3.38731003e-10 3.71888089e-10 4.08208981e-10
 4.47987410e-10 4.91543583e-10 5.39226490e-10 5.91416415e-10
 6.48527650e-10 7.11011437e-10 7.79359158e-10 8.54105792e-10
 9.35833652e-10 1.02517644e-09 1.12282362e-09 1.22952520e-09
 1.34609681e-09 1.47342529e-09 1.61247472e-09 1.76429285e-09
 1.93001819e-09 2.11088755e-09 2.30824424e-09 2.52354696e-09
 2.75837931e-09 3.01446017e-09 3.29365481e-09 3.59798691e-09
 3.92965156e-09 4.29102926e-09 4.68470098e-09 5.11346446e-09
 5.58035175e-09 6.088648